# =========================
# Application
# =========================
spring.application.name=auth-service
server.port=8080

# =========================
# Datasource (PostgreSQL)
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5433/authdb
spring.datasource.username=postgres
spring.datasource.password=sabrine123
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# =========================
# Flyway (migration DB)
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# =========================
# Logging
# =========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
